services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: serverscheduler-backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8080
      - DB_PATH=/app/data/serverscheduler.db
    networks:
      - serverscheduler-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: serverscheduler-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - serverscheduler-network
    restart: unless-stopped

networks:
  serverscheduler-network:
    driver: bridge

volumes:
  data:
    driver: local 