name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        timeout-minutes: 5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        timeout-minutes: 5
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main .
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          fi
        timeout-minutes: 5 