name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Add any required services here (e.g., databases)
      sqlite:
        image: alpine:latest
        options: >-
          --health-cmd "echo 'SQLite is ready'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc musl-dev

      - name: Run tests
        run: |
          go test -v ./...
        env:
          CGO_ENABLED: 1
          DB_PATH: /tmp/test.db

      - name: Run tests with race detector
        run: |
          go test -race -v ./...
        env:
          CGO_ENABLED: 1
          DB_PATH: /tmp/test.db

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out -v ./...
          go tool cover -func=coverage.out
        env:
          CGO_ENABLED: 1
          DB_PATH: /tmp/test.db 